"""Forge marketplace structure: scaffold a new app, or adapt an existing repo.

MIT-clean, native Python. Mirrors the Buildly ForgeAppTemplate (MIT) structure —
BUILDLY.yaml manifest, devdocs/{features,bugs,reviews}, .ai policy, marketplace/
screenshots — as additive files. Never modifies existing application code; only
adds missing Forge scaffolding.
"""

from __future__ import annotations

import re
from pathlib import Path

from pydantic import BaseModel


class ForgeResult(BaseModel):
    output_dir: str
    files_written: list[str]
    files_skipped: list[str]      # already existed; left untouched
    manifest_id: str


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") or "app"


def _manifest(name: str, description: str, category: str) -> str:
    return (
        "# BUILDLY.yaml - Marketplace Manifest\n"
        "# Generated by Buster (Buildly.io). Edit to describe your app.\n\n"
        f"id: {_slug(name)}\n"
        f"name: {name}\n"
        f"description: {description[:160]}\n"
        "version: 0.1.0\n"
        f"category: {category}\n"
        "tags:\n  - buildly\n  - forge\n"
        "author:\n  name: \n  email: \n  url: https://buildly.io\n"
        "license: MIT\n"
        "repository: \n"
    )


_AGENT_POLICY = """# AI Agent Policy

This repository participates in Buildly's AI-native workflow.

- Agents must respect feature and issue contracts.
- Inferred conclusions are proposals, not truth, until a human approves them.
- No secrets in commits. No auto-merge of pull requests.
- Generated docs live under `devdocs/`.
"""

_FEATURE_TEMPLATE = """# Feature: <name>

- **Status:** proposed
- **Intent:**
- **Scope (included):**
- **Scope (excluded):**
- **Acceptance criteria:**
"""

_BUG_TEMPLATE = """# Bug: <summary>

- **Severity:**
- **Steps to reproduce:**
- **Expected:**
- **Actual:**
"""


def _forge_files(name: str, description: str, category: str) -> dict[str, str]:
    return {
        "BUILDLY.yaml": _manifest(name, description, category),
        ".ai/AGENT_POLICY.md": _AGENT_POLICY,
        "devdocs/features/FEATURE_TEMPLATE.md": _FEATURE_TEMPLATE,
        "devdocs/bugs/BUG_TEMPLATE.md": _BUG_TEMPLATE,
        "devdocs/reviews/.gitkeep": "",
        "marketplace/screenshots/.gitkeep": "",
    }


def adapt_to_marketplace(
    repo_dir: str, name: str, description: str = "", category: str = "starter",
    force: bool = False,
) -> ForgeResult:
    """Add Forge/marketplace scaffolding to an EXISTING repo. Additive only:
    existing files are never overwritten (unless force). No app code is touched."""
    root = Path(repo_dir).expanduser()
    root.mkdir(parents=True, exist_ok=True)
    written, skipped = [], []
    for rel, content in _forge_files(name or root.name, description, category).items():
        path = root / rel
        if path.exists() and not force:
            skipped.append(rel)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        written.append(rel)
    return ForgeResult(output_dir=str(root), files_written=sorted(written),
                       files_skipped=sorted(skipped), manifest_id=_slug(name or root.name))


def new_forge_app(
    output_dir: str, name: str, description: str = "", category: str = "starter",
) -> ForgeResult:
    """Create a NEW Forge app skeleton (Forge structure + a minimal README).

    A full clone of ForgeAppTemplate can be layered on later; this produces the
    marketplace-required structure offline, with no network dependency.
    """
    root = Path(output_dir).expanduser()
    if root.exists() and any(root.iterdir()):
        raise FileExistsError(f"{root} is not empty.")
    root.mkdir(parents=True, exist_ok=True)
    (root / "README.md").write_text(
        f"# {name}\n\nA Buildly Forge app. Structure generated by Buster.\n\n"
        "See `BUILDLY.yaml` for the marketplace manifest and `devdocs/` for docs.\n"
    )
    res = adapt_to_marketplace(str(root), name, description, category)
    res.files_written = sorted([*res.files_written, "README.md"])
    return res
