"""FastAPI + SQLAlchemy Buildly-module generator (native Python, MIT).

Given a module name and model names, generate a small, runnable service with
CRUD routes. Safe by design: refuses to overwrite an existing non-empty target
unless ``force`` is set, and only writes inside the chosen output directory.
"""

from __future__ import annotations

import re
from pathlib import Path

from pydantic import BaseModel, Field


class ScaffoldPlan(BaseModel):
    module_name: str
    models: list[str] = Field(default_factory=list)
    output_dir: str
    framework: str = "fastapi"     # fastapi (django reserved for later)
    include_docker: bool = True


class ScaffoldResult(BaseModel):
    output_dir: str
    files_written: list[str]
    models: list[str]
    framework: str


def _class_name(name: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", name.strip())
    return "".join(p[:1].upper() + p[1:] for p in parts if p) or "Item"


def _table_name(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", name.strip().lower()).strip("_") or "item"
    return slug + "s"


def _var_name(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.strip().lower()).strip("_") or "item"


def _main_py(module_name: str, models: list[str]) -> str:
    header = ('''"""Generated Buildly module — {name}.

FastAPI + SQLAlchemy with CRUD routes. Generated by Buster (Buildly.io).
Edit freely; this is your code.
"""

from fastapi import Depends, FastAPI, HTTPException
from pydantic import BaseModel
from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.orm import Session, declarative_base, sessionmaker

DATABASE_URL = "sqlite:///./database.db"
engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

''').replace("{name}", module_name)

    orm_blocks, schema_blocks, route_blocks = [], [], []
    for m in models:
        cls, table, var = _class_name(m), _table_name(m), _var_name(m)
        orm_blocks.append(
            f'class {cls}(Base):\n'
            f'    __tablename__ = "{table}"\n'
            f'    id = Column(Integer, primary_key=True, index=True)\n'
            f'    name = Column(String, index=True)\n'
        )
        schema_blocks.append(
            f'class {cls}In(BaseModel):\n'
            f'    name: str\n\n'
            f'class {cls}Out({cls}In):\n'
            f'    id: int\n\n'
            f'    class Config:\n'
            f'        from_attributes = True\n'
        )
        route_blocks.append(f'''
@app.get("/{table}", response_model=list[{cls}Out], tags=["{cls}"])
def list_{table}(db: Session = Depends(get_db)):
    return db.query({cls}).all()


@app.post("/{table}", response_model={cls}Out, tags=["{cls}"])
def create_{var}(payload: {cls}In, db: Session = Depends(get_db)):
    obj = {cls}(**payload.model_dump())
    db.add(obj); db.commit(); db.refresh(obj)
    return obj


@app.get("/{table}/{{item_id}}", response_model={cls}Out, tags=["{cls}"])
def get_{var}(item_id: int, db: Session = Depends(get_db)):
    obj = db.get({cls}, item_id)
    if obj is None:
        raise HTTPException(404, "{cls} not found")
    return obj


@app.delete("/{table}/{{item_id}}", tags=["{cls}"])
def delete_{var}(item_id: int, db: Session = Depends(get_db)):
    obj = db.get({cls}, item_id)
    if obj is None:
        raise HTTPException(404, "{cls} not found")
    db.delete(obj); db.commit()
    return {{"deleted": item_id}}
''')

    body = (
        header
        + "\n\n".join(orm_blocks) + "\n\n"
        + "\n".join(schema_blocks) + "\n\n"
        + "Base.metadata.create_all(bind=engine)\n\n"
        + f'app = FastAPI(title="{module_name}", version="1.0")\n\n\n'
        + '@app.get("/health", tags=["meta"])\ndef health():\n    return {"status": "ok"}\n'
        + "".join(route_blocks)
    )
    return body


def _requirements() -> str:
    return "fastapi\nuvicorn[standard]\npydantic>=2\nsqlalchemy>=2\n"


def _run_sh() -> str:
    return ('#!/bin/sh\n'
            'echo "Starting FastAPI service on :8000…"\n'
            'uvicorn main:app --host 0.0.0.0 --port 8000 --reload\n')


def _dockerfile() -> str:
    return ("FROM python:3.12-slim\n"
            "WORKDIR /app\n"
            "COPY requirements.txt .\n"
            "RUN pip install --no-cache-dir -r requirements.txt\n"
            "COPY . .\n"
            'CMD ["sh", "run.sh"]\n')


def _readme(module_name: str, models: list[str]) -> str:
    model_list = "\n".join(f"- `{_class_name(m)}` (`/{_table_name(m)}`)" for m in models)
    return (f"# {module_name}\n\n"
            f"A Buildly module generated by Buster.\n\n"
            f"## Models\n\n{model_list}\n\n"
            f"## Run\n\n```sh\npip install -r requirements.txt\nsh run.sh\n```\n\n"
            f"Then open http://localhost:8000/docs\n")


def scaffold_fastapi_module(plan: ScaffoldPlan, force: bool = False) -> ScaffoldResult:
    out = Path(plan.output_dir).expanduser()
    if out.exists() and any(out.iterdir()) and not force:
        raise FileExistsError(
            f"{out} is not empty. Choose an empty directory or pass force=True."
        )
    out.mkdir(parents=True, exist_ok=True)

    models = [m for m in plan.models if m.strip()] or ["Item"]
    files: dict[str, str] = {
        "main.py": _main_py(plan.module_name, models),
        "requirements.txt": _requirements(),
        "run.sh": _run_sh(),
        "README.md": _readme(plan.module_name, models),
    }
    if plan.include_docker:
        files["Dockerfile"] = _dockerfile()

    written = []
    for name, content in files.items():
        path = out / name
        path.write_text(content)
        if name == "run.sh":
            path.chmod(0o755)
        written.append(name)

    return ScaffoldResult(output_dir=str(out), files_written=sorted(written),
                          models=models, framework=plan.framework)
